language: go
sudo: required

before_script:
  - go get -u github.com/mattn/goveralls

script: # to allow coverage pass, change repo name to github.com/mellanox
  - cd ../../ && mv Mmduh-483 Mellanox && cd Mellanox/ib-kubernetes/
  - make
  - sudo -E env "PATH=$PATH" make test
  - sudo -E env "PATH=$PATH" make test-coverage
  - for pkg in `ls test/coverage/*.cover`; do goveralls -coverprofile=$pkg -service=travis-ci; done
  - make image

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  # Push image to Dockerhub on merge to master
  - provider: script
    skip_cleanup: true
    script: >
     bash -c '
     docker push $IMAGE_NAME;
     echo done'
    on:
      branch: master
