[[override]]
  name = "k8s.io/client-go"
  version = "v0.15.10"

 [[constraint]]
 name = "k8s.io/apimachinery"
 version = "0.15.10"
 
 [[constraint]]
 name = "k8s.io/api"
 version = "v0.15.10"

[[override]]
  name = "k8s.io/utils"
  source = "https://github.com/kubernetes/utils.git"
  revision = "861946025e3491219eaccb1bf693e23df70c2fa8"

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/golang/crypto.git"
  revision = "69ecbb4d6d5dab05e49161c6e77ea40a030884e1"

[[override]]
  name = "golang.org/x/time"
  source = "https://github.com/golang/time.git"
  revision = "555d28b269f0569763d25dbe1a237ae74c6bcc82"

[[override]]
  name = "golang.org/x/oauth2"
  source = "https://github.com/golang/oauth2.git"
  revision = "bf48bf16ab8d622ce64ec6ce98d2c98f916b6303"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/k8snetworkplumbingwg/network-attachment-definition-client"
  source = "https://github.com/k8snetworkplumbingwg/network-attachment-definition-client.git"
  revision = "0ee521d560613bfe2d2c775159f93c2413a39db2"

[prune]
  go-tests = true
  unused-packages = true
