apiVersion: v1
kind: ConfigMap
metadata:
  name: ib-kubernetes-config
  namespace: kube-system
data:
  PLUGIN: "ufm"
  PERIODIC_UPDATE: "5"
  RANGE_START: "02:00:00:00:00:00:00:00"
  RANGE_END: "02:FF:FF:FF:FF:FF:FF:FF"
